### ISSUE TITLE
Avoid wrapper element

### ISSUE THREAD

**Issue by jimfranke** [zaceno/hyperapp-nestable#5]
Hi @zaceno,,
Is it possible to avoid the wrapping element in which the nested app is rendered (default x-), and for example render to a DocumentFragment?
Regards,
Jim

**Comment by zaceno** [comment]
@jimfranke

I don’t think so, sorry. I’ve experimented with replacing the wrapping element in its parent with the root element of the nestable view. So that in effect the wrapping element is only a temporary placeholder. But I couldn’t get it to work dependably.

**Comment by christiankaindl** [comment]
@jimfranke Depending on what browsers you need to support, you could use the CSS feature `display: contents`

Article
https://bitsofco.de/how-display-contents-works/

Browser compatibility:
https://developer.mozilla.org/en-US/docs/Web/CSS/display#Browser_compatibility

**Comment by zaceno** [comment]
@christiankaindl Thanks for the tip about `display: contents` -  very useful css rule!

@jimfranke Thanks for raising the question, but I'm going to close for now. I don't expect to work on this in the future. Sorry!
